name: BetterSkyBlock
main: br.com.syrxcraft.betterskyblock.BetterSkyBlock
version: @VERSION@
author: brunoxkk0
depend: [GriefDefender, WorldEdit]
softdepend: [ PlaceholderAPI, BossShopPro ]
load: POSTWORLD


commands:

  island:
      description: BetterSkyBlock main command.
      usage: is help
      aliases: [is, isl, bsis]

permissions:

  betterskyblock.admin:
    default: op
    children:
      betterskyblock.cmd.spawn: true
      betterskyblock.cmd.biome.list: true
      betterskyblock.cmd.reset: true
      betterskyblock.cmd.private: true
      betterskyblock.cmd.public: true
      betterskyblock.cmd.delete.other: true
      betterskyblock.set.spawn: true
      betterskyblock.set.biome: true
      betterskyblock.set.biome.all: true
      betterskyblock.set.radius: true
      betterskyblock.noteleportdelay: true
      betterskyblock.override: true
      betterskyblock.leaveisland: true

  betterskyblock.cmd.biome.list:
    default: true
  betterskyblock.cmd.reset:
    default: true
  betterskyblock.cmd.private:
    default: true
  betterskyblock.cmd.public:
    default: true
  betterskyblock.cmd.delete.other:
    default: op
  betterskyblock.set.spawn:
    default: true
  betterskyblock.set.biome:
    default: true
  betterskyblock.set.biome.all:
    default: op
  betterskyblock.set.radius:
    default: op
  betterskyblock.noteleportdelay:
    default: op
  betterskyblock.override:
    default: op
  betterskyblock.leaveisland:
    default: op